### PR TITLE
Updated to latest

### PR DESCRIPTION
**Pull request by gents83**
Integrating latest updated and fixes of zeux

### CODE REVIEW

**Comment by oisyn** [comment]
It seems the bindings are a bit out of date. https://github.com/gwihlidal/meshopt-rs/pull/32 fixes them on master.

**Comment by gents83** [comment]
@gwihlidal if you could push this at least it'll be up-to-date 👍

**Comment by gents83** [comment]
PS: I've fixed also all clippy warnings

**Comment by gwihlidal** [comment]
Thank you @gents83 ! I'm going to add a couple of you as co-maintainers to this repro (as well as crates.io) to help me keep things up to date and improving. Does that sound good to you?

**Comment by gents83** [comment]
Sure! That would be super fine :)

**Comment by gwihlidal** [comment]
Done =)

**Pull request merged**
